version: "3.9"

networks:
  club_network:
    external: true

volumes:
  pg_data:

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - club_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  api:
    image: your-registry/club-api:latest
    environment:
      API_ENV: ${API_ENV}
      API_JWT_SECRET: ${API_JWT_SECRET}
      API_CORS_ORIGINS: ${API_CORS_ORIGINS}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - club_network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  web:
    image: your-registry/club-web:latest
    networks:
      - club_network
    deploy:
      replicas: 2

  flutter_web:
    image: your-registry/club-flutter-web:latest
    networks:
      - club_network
    deploy:
      replicas: 2

  nginx:
    image: your-registry/club-nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - club_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
